### ISSUE TITLE
Failed connections appear to cause memory leaks and don't timeout

### ISSUE THREAD

**Issue by SonarBeserk** [obsilp/rmnp-csharp#2]
I was testing the code by running it in unity and consuming the Client class. I notice that memory stays about the same if a connection succeeds but memory usage steadily climbs on a failure. It appears to not actually trigger a timeout in my testing.

**Comment by SonarBeserk** [comment]
Looking into the issue further https://github.com/obsilp/rmnp-csharp/blob/d2dcda120788301ddba49d9aa07a111e2df50847/Connection.cs#L208 will always return before hitting timeout logic due to the fact the default connection state is disconnected. Removing this check corrects the ability for connections to timeout.

**Comment by tim-oster** [comment]
Thats strange, the example I pushed works fine with this check. Are you sure that the State was
"Disconnected" when you debugged? Because it should have been at least "Connecting" as every connection state is set when the Connection object is acquired. (Connection.cs#L84)

**Comment by SonarBeserk** [comment]
I gave it a try today and it is working correctly. I am unsure of why it wasn't yesterday and I wouldn't think it would be related to the buffer changes but I would say it's fine for now.
